/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_utils_PictureTransformUtil */

#ifndef _Included_com_example_utils_PictureTransformUtil
#define _Included_com_example_utils_PictureTransformUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_utils_PictureTransformUtil
 * Method:    ImgToGrey
 * Signature: (III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_utils_PictureTransformUtil_ImgToGrey
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
